POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "cc","password": "Pass1234!", "email": "adam@mail.com","Role":"Customer" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "cc", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token db1ad9d1941c35ea957b4793ec0086e08b8fee81
###

POST http://127.0.0.1:8000/postinboundloans 
Content-Type: application/json
Authorization: token db1ad9d1941c35ea957b4793ec0086e08b8fee81

{"Amount":"2000"}

###

GET http://127.0.0.1:8000/getinboundloans 
Content-Type: application/json
Authorization: token db1ad9d1941c35ea957b4793ec0086e08b8fee81

# {"ProviderID":5}

###

Post http://127.0.0.1:8000/setbankparameter 
Content-Type: application/json
Authorization: token 95ede9ec8da251be295e4ba5c077ece76ca52aa0

{
"MinAmount":100,
"MaxAmount":10000,
"NumberOfPayments":10

}


###

POST http://127.0.0.1:8000/postoutboundloans 
Content-Type: application/json
Authorization: token ae34f3afc62822caf03dbf63ba9b801cc3dcda23

{"Amount":2000}


###

GET http://127.0.0.1:8000/getoutboundloans 
Content-Type: application/json
Authorization: token ae34f3afc62822caf03dbf63ba9b801cc3dcda23

{"CustomerID":10000}

###

GET http://127.0.0.1:8000/postpayment 
Content-Type: application/json
Authorization: token ae34f3afc62822caf03dbf63ba9b801cc3dcda23

{"LoanID":1}