POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "pppppp","password": "Pass1234!", "email": "adam@mail.com","Role":"Provider" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "c", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token e0108ed18d3302e1d86cfdc50e31d000c8d787bb
###

POST http://127.0.0.1:8000/postinboundloans 
Content-Type: application/json
Authorization: token b5260099d10ad76c7ecca41e6d2b8e035047828c

{"Amount":"2000000"}

###

GET http://127.0.0.1:8000/getinboundloans 
Content-Type: application/json
Authorization: token 24415833242863182def77040d689fb05d032f56

{"ProviderID":1}

###

Post http://127.0.0.1:8000/setbankparameter 
Content-Type: application/json
Authorization: token 858adb38fa38dddc8465bd3f2bdabaee63f214fa

{
"MinAmount":100,
"MaxAmount":10000,
"NumberOfPayments":10,
"InterestRate":10

}


###

POST http://127.0.0.1:8000/postoutboundloans 
Content-Type: application/json
Authorization: token 287881b303457e1662bbe84d3f624a00c2d4c565

{"Amount":5000}


###

GET http://127.0.0.1:8000/getoutboundloans 
Content-Type: application/json
Authorization: token 287881b303457e1662bbe84d3f624a00c2d4c565

{"CustomerID":10000}

###

POST http://127.0.0.1:8000/postpayment 
Content-Type: application/json
Authorization: token 287881b303457e1662bbe84d3f624a00c2d4c565

{"LoanID":1}