POST http://127.0.0.1:8000/LoanApp/register 
Content-Type: application/json

{ "username": "qp","password": "Pass1234!", "email": "adam@mail.com","Role":"Provider" }

###

POST http://127.0.0.1:8000/LoanApp/login 
Content-Type: application/json

{ "username": "c", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token e0108ed18d3302e1d86cfdc50e31d000c8d787bb
###

POST http://127.0.0.1:8000/LoanApp/postinboundloans 
Content-Type: application/json
Authorization: token 0dd65aced1171d9afaa77c4d4017ae42890780ef

{"Amount":2000000}

###

POST  http://127.0.0.1:8000/LoanApp/getinboundloans 
Content-Type: application/json
Authorization: token 0dd65aced1171d9afaa77c4d4017ae42890780ef

# {"ProviderID":1}

###

Post http://127.0.0.1:8000/LoanApp/setbankparameter 
Content-Type: application/json
Authorization: token 858adb38fa38dddc8465bd3f2bdabaee63f214fa

{
"MinAmount":100,
"MaxAmount":10000,
"NumberOfPayments":10,
"InterestRate":10

}


###

POST http://127.0.0.1:8000/LoanApp/postoutboundloans 
Content-Type: application/json
Authorization: token 287881b303457e1662bbe84d3f624a00c2d4c565

{"Amount":5000}


###

POST http://127.0.0.1:8000/LoanApp/getoutboundloans 
Content-Type: application/json
Authorization: token 287881b303457e1662bbe84d3f624a00c2d4c565

{"CustomerID":10000}

###

POST http://127.0.0.1:8000/LoanApp/postpayment 
Content-Type: application/json
Authorization: token 287881b303457e1662bbe84d3f624a00c2d4c565

{"LoanID":1}