# Generated by Django 4.2.3 on 2023-07-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRestProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=100)),
                ('Role', models.CharField(choices=[('Provider', 'Provider'), ('Customer', 'Customer'), ('Personnel', 'Personnel')], max_length=30)),
            ],
        ),
    ]
