# Generated by Django 4.2.3 on 2023-07-31 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRestProject', '0002_tempuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='PersonnelProfile',
        ),
        migrations.DeleteModel(
            name='ProviderProfile',
        ),
    ]
