# Generated by Django 4.2.3 on 2023-07-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRestProject', '0003_remove_personnelprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'permissions': [('show_loans', 'Can show his loans'), ('give_loan', 'Can make inbound loan')]},
        ),
    ]
