# Generated by Django 4.2.3 on 2023-07-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRestProject', '0004_alter_provider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={},
        ),
    ]
