# Generated by Django 4.2.3 on 2023-07-31 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRestProject', '0005_alter_provider_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='CustomerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
