# Generated by Django 4.2.3 on 2023-08-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRestProject', '0006_bank_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='InterestRate',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundloan',
            name='InterestAmount',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
