# Generated by Django 4.2.3 on 2023-08-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRestProject', '0007_bank_interestrate_outboundloan_interestamount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'permissions': (('trail', 'Friendly permission description'),)},
        ),
    ]
