# Generated by Django 4.2.3 on 2023-08-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRestProject', '0008_alter_provider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('trail', 'Friendly permission description'),)},
        ),
    ]
