# Generated by Django 4.2.3 on 2023-08-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRestProject', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('trail', 'Friendly permission description'),)},
        ),
    ]
