# Generated by Django 4.2.3 on 2023-08-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRestProject', '0013_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_inboundloans', 'view inbounds'), ('add_inboundloans', 'add inboundloans'), ('view_outboundloans', 'view outboundloans'), ('add_outboundloans', 'add outboundloans'), ('add_payment', 'add payment'), ('add_bankparameter', 'add bankparameter'))},
        ),
    ]
